import logging
from typing import List, Optional, AsyncIterator
import os
import httpx
from app.config import settings
from app.schemas.chat import Message

logger = logging.getLogger(__name__)

class LLMService:
    """
    Modular LLM service supporting Google Gemini and OpenAI-compatible providers.
    Keeps API keys and direct provider logic strictly on the server-side.
    """

    def __init__(self):
        self.provider = settings.LLM_PROVIDER.lower()
        self.model = settings.LLM_MODEL
        self.api_key = settings.get_api_key()

    async def generate_response(
        self,
        prompt: str,
        history: Optional[List[Message]] = None,
        system_instruction: Optional[str] = None
    ) -> str:
        """
        Generates a non-streaming completion given a user prompt, conversation history,
        and an optional system instruction.
        """
        history = history or []

        if not self.api_key:
            # Fallback helpful message if API key isn't provided yet
            return (
                "⚠️ API Key Not Configured. Please set GEMINI_API_KEY or LLM_API_KEY "
                "in your `.env` file to enable live AI responses."
            )

        if self.provider in ("google", "gemini"):
            return await self._generate_gemini(prompt, history, system_instruction)
        elif self.provider in ("openai", "groq"):
            return await self._generate_openai_compatible(prompt, history, system_instruction)
        else:
            # Default to Gemini
            return await self._generate_gemini(prompt, history, system_instruction)

    async def _generate_gemini(
        self,
        prompt: str,
        history: List[Message],
        system_instruction: Optional[str]
    ) -> str:
        """
        Calls Google Gemini API using native REST v1beta endpoint.
        Uses gemini-3.8-flash by default.
        """
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

        contents = []

        # Add history
        for msg in history:
            role = "user" if msg.role == "user" else "model"
            contents.append({
                "role": role,
                "parts": [{"text": msg.content}]
            })

        # Add current user prompt
        contents.append({
            "role": "user",
            "parts": [{"text": prompt}]
        })

        payload = {
            "contents": contents
        }

        if system_instruction:
            payload["systemInstruction"] = {
                "parts": [{"text": system_instruction}]
            }

        async with httpx.AsyncClient(timeout=60.0) as client:
            headers = {
                "Content-Type": "application/json",
                "User-Agent": "aistudio-build"
            }
            resp = await client.post(url, json=payload, headers=headers)
            
            if resp.status_code != 200:
                logger.error(f"Gemini API error ({resp.status_code}): {resp.text}")
                return f"Error from LLM API: {resp.text}"

            data = resp.json()
            candidates = data.get("candidates", [])
            if candidates and "content" in candidates[0]:
                parts = candidates[0]["content"].get("parts", [])
                if parts and "text" in parts[0]:
                    return parts[0]["text"]
            return "No response generated by model."

    async def _generate_openai_compatible(
        self,
        prompt: str,
        history: List[Message],
        system_instruction: Optional[str]
    ) -> str:
        """
        Calls OpenAI-compatible /v1/chat/completions endpoint.
        """
        base_url = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
        url = f"{base_url}/chat/completions"

        messages = []
        if system_instruction:
            messages.append({"role": "system", "content": system_instruction})

        for msg in history:
            messages.append({"role": msg.role, "content": msg.content})

        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": 0.7
        }

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(url, json=payload, headers=headers)
            if resp.status_code != 200:
                logger.error(f"OpenAI API error: {resp.text}")
                return f"LLM Provider Error: {resp.text}"

            data = resp.json()
            return data["choices"][0]["message"]["content"]

llm_service = LLMService()
